spring:
  application:
    name: theater

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker
  data:
    mongodb:
      database: theater
      host: theaterdb
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/